{% set name = "gnuradio-satellites" %}
{% set version = "4.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/daniestevez/gr-satellites/archive/v{{ version }}.tar.gz
  sha256: 3bfc1d75818154fc7c9dbd0427c850f09b97e3757f9449f715d45d32aaa5e18d

build:
  number: 4
  run_exports:
    - {{ pin_subpackage('gnuradio-satellites', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - bzip2  # [not win]
    - cmake
    - make  # [not win]
    - ninja  # [win]
    - pkg-config  # [not win]
    # cross-compilation requirements
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]

  host:
    - boost-cpp
    - gnuradio-core
    - pip  # [win]
    - pybind11
    - python
    - numpy
    - volk

  run:
    - construct >=2.9
    - gnuradio-zeromq
    - matplotlib-base
    - numpy
    - python
    - pyyaml
    - requests

test:
  commands:
    # verify that commands run (will print usage statement)
    {% set cmds = ["gr_satellites", "jy1sat_ssdv", "smog_p_spectrum"] %}
    {% for cmd in cmds %}
    - {{ cmd }} || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - {{ cmd }} || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]
    {% endfor %}

    # verify that (some) headers get installed
    - test -f $PREFIX/include/satellites/api.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\satellites\\api.h exit 1  # [win]

    # verify that libraries get installed
    - test -f $PREFIX/lib/lib{{ name }}${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\{{ name }}.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\{{ name }}.lib exit 1  # [win]

    # verify that (some) GRC blocks get installed
    {% set blocks = ["satellites_decode_rs", "satellites_ax100_decode"] %}
    {% set blocks = blocks + ["satellites_check_crc"] %}

    {% for block in blocks %}
    - test -f $PREFIX/share/gnuradio/grc/blocks/{{ block }}.block.yml  # [not win]
    - if not exist %PREFIX%\\Library\\share\\gnuradio\\grc\\blocks\\{{ block }}.block.yml exit 1  # [win]
    {% endfor %}

  imports:
    - satellites

about:
  home: https://github.com/daniestevez/gr-satellites
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A collection of decoders for Amateur satellites
  description: |
    gr-satellites is a GNU Radio out-of-tree module with a collection of telemetry decoders for Amateur satellites.
  doc_url: https://gr-satellites.readthedocs.io/en/latest/index.html
  dev_url: https://github.com/daniestevez/gr-satellites

extra:
  recipe-maintainers:
    - petrushy
    - ryanvolz
    - daniestevez
