azure: {store_build_artifacts: true}
bot:
  automerge: true
  abi_migration_branches:
   - 3.x
build_platform: {osx_arm64: osx_64}
conda_forge_output_validation: true
provider: {linux_aarch64: default, linux_ppc64le: default}
test_on_native_only: true
